---
# AUTO: scripts/test-repo-key.sh --pam (не редактировать)
# Pubkey: ~/.itwarranty-pam/test-access/<name>/ (admin HOME при ansible-playbook)
pam_operators_test:
  - name: tester-01
    email: tester-01@example.com
    pubkey: "{{ lookup('file', lookup('env', 'HOME') ~ '/.itwarranty-pam/test-access/tester-01/tester-01.key.pub') }}"
    mfa_secret: XMY6KMB4EUVZBQB5F3C7356CHO6FTMON
    access: jump
    permit_open:
      - "10.0.1.10:22"
